### ISSUE TITLE
How read the information on the Map

### ISSUE THREAD

**Issue by hayatbellafkih** [dk379/asn-tryst#5]
Hello,

I see  the presentation [pdf](https://ripe71.ripe.net/presentations/102-RIPE71_ASNtryst_RIPE_Atlas_Hackathon_Project.pdf.) of the project and the  [video](https://ripe71.ripe.net/archives/video/1146/)  presentation. My question is about Reading the data on the Map. For example, what ASN represents a dot as each dot presents a change from ASN to ASN.

Thanks in advance.

Best regards,

Hayat Bellafkih

**Comment by cteusche-ripencc** [comment]
Hi Hayat,
Not sure I understand your question correctly but the basic data for the map are traceroutes. But since traceroute do not contain ASNs but IPs, we got this information from BGP data via RIPEstat. [1] is a mapping between an IP address and its originating ASN. 
You can of course map additional information e.g. an ASN name with [2] based on information coming from the Regional Internet Registries.

Hth,
Christian

[1] https://stat.ripe.net/docs/data_api#NetworkInfo
[2] https://stat.ripe.net/docs/data_api#AsOverview

**Comment by hayatbellafkih** [comment]
Thanks  for the details.
 For example, giving a change from  IP1 (AS10) to (IP2 (AS20) in a traceroute from _probe1_ to destination _d_, the objective of the project, I think, is displaying WHERE this change  is done, and a change  is one of the dots on a [Map](http://asntryst.com/).
 My question :  a dot represents the position of router IP1, the router IP2 or other?
Thanks in advance.
Best regards,

Hayat

**Comment by cteusche-ripencc** [comment]
I see, the answer is that it is the location where both IPs are located, given - and that is the tricky part - there is reliable information on the IP location. 
The mapping between (topological) IP addresses and geographical locations is not easy to get right. The RIPE NCC started a project to collect this data more reliably, see https://openipmap.ripe.net for details.

Christian

**Comment by hayatbellafkih** [comment]
I get the answer .

Thanks.

Hayat
